"""CLI help text — core vs ops progressive disclosure (composer surface)."""

def cli_surface_help() -> String:
    # Happy-path (Essential Fala): one journal, run lifecycle, inspect.
    # Ops (progressive disclosure): maintain-journal, gc, projections rebuild, and bridge verbs.
    var text = "# core — package/run/inspect one journal\n"
    text += "schema impulse\nschema model\n"
    text += "db init\ndb migrate\ndb status\ndb schema\ndoctor\n"
    text += "create-run\n"
    text += "impulses create\nprocesses schedule\nprocesses cancel\nprocesses timeout\nassociations append\n"
    text += "runs list\nruns inspect\nruns observe\n"
    text += "runs start\nruns wait\nruns complete\nruns fail\n"
    text += "runs request-cancel\nruns cancel\nruns timeout\n"
    text += "commands list\ncommands inspect\n"
    text += "events list\nevents validate-schema\n"
    text += "processes list\nprocesses inspect\n"
    text += "impulses list\nimpulses inspect\n"
    text += "impulse-types list\nimpulse-types inspect\n"
    text += "impulse-relations list\nimpulse-relations inspect\n"
    text += "relations list\nrelations inspect\n"
    text += "associations list\nassociations inspect\n"
    text += "reactions list\nreactions inspect\n"
    text += "homeostats list\nhomeostats open\nhomeostats reopen\n"
    text += "homeostats complete\nhomeostats cancel\nhomeostats expire\n"
    text += "homeostat open (alias)\nhomeostat reopen (alias)\nhomeostat complete (alias)\n"
    text += "homeostat cancel (alias)\nhomeostat expire (alias)\n"
    text += "projections list\n"
    text += "trace\ndiagnose-waits\n"
    text += "# ops — optional operator tools (not required to compose a flow)\n"
    text += "ops maintain-journal (alias: maintain-journal)\n"
    text += "ops gc (alias: gc)\n"
    text += "ops projections rebuild (alias: projections rebuild)\n"
    text += "bridge list\nbridges list (alias: bridge list)\nbridge deliver\nbridge export\nbridge import\n"
    text += "db vacuum\n"
    text += "init\n"
    text += "archive-run (native boundary)\narchive-gc (native boundary)\n"
    text += "schema fala-package (native boundary)\n"
    text += "replay-execution (native boundary)\n"
    text += "export (native boundary)"
    return text

