"""CLI help text — core vs ops progressive disclosure (composer surface)."""

def cli_surface_help() -> String:
    # Happy-path (Essential Fala): one journal, run lifecycle, inspect.
    # Ops (progressive disclosure): maintain-journal, gc, projections rebuild, and bridge verbs.
    var text = "# core — package/run/inspect one journal\n"
    text += "schema impulse\nschema model\n"
    text += "db init\ndb migrate\ndb status\ndb schema\ndoctor\n"
    text += "create-run\n"
    text += "impulses create\nprocesses schedule\nprocesses cancel\nprocesses timeout\nassociations append\n"
    text += "runs list\nruns inspect\nruns observe\n"
    text += "runs start\nruns wait\nruns complete\nruns fail\n"
    text += "runs request-cancel\nruns cancel\nruns timeout\n"
    text += "commands list\ncommands inspect\n"
    text += "events list\nevents validate-schema\n"
    text += "processes list\nprocesses inspect\n"
    text += "impulses list\nimpulses inspect\n"
    text += "impulse-types list\nimpulse-types inspect\n"
    text += "impulse-relations list\nimpulse-relations inspect\n"
    text += "associations list\nassociations inspect\n"
    text += "reactions list\nreactions inspect\n"
    text += "homeostats list\nhomeostats open\nhomeostats reopen\n"
    text += "homeostats complete\nhomeostats cancel\nhomeostats expire\n"
    text += "projections list\n"
    text += "trace\ndiagnose-waits\n"
    text += "graph expand --package PATH\n"
    text += "graph validate --package PATH\n"
    text += "graph fingerprint --package PATH\n"
    text += "graph diff --before PATH --after PATH\n"
    text += "explain --db PATH --package PATH --run-id ID [--process-id ID | --terminal ID]\n"
    text += "rehearse --package PATH --fixture PATH --path-id ID --journal PATH --report PATH\n"
    text += "# ops — optional operator tools (not required to compose a flow)\n"
    text += "ops maintain-journal (alias: maintain-journal)\n"
    text += "ops gc (alias: gc)\n"
    text += "ops projections rebuild (alias: projections rebuild)\n"
    text += "bridge list\nbridge deliver\nbridge export\nbridge import\n"
    text += "db vacuum\n"
    text += "init"
    return text

