from std.collections import List
from fala.reactions import put_bytes, resolve_uri, is_fala_reaction_uri, digest_from_fala_reaction_uri, content_address_json, FileReactionStore

def _check(condition: Bool, message: String) raises:
    if not condition:
        raise Error("reaction parity smoke: " + message)

def main() raises:
    var root = "/tmp/fala-reaction-native-smoke"
    var store = FileReactionStore(root)
    _check(store.location() == root, "reaction store reports configured root")
    var existing = store.list_blob_digests()
    if len(existing) > 0:
        _ = store.delete_blobs(existing^)
    var kept = put_bytes(root, "a", "demo.txt")
    var removed = put_bytes(root, "b", "removed.txt")
    var orphan = put_bytes(root, "c", "orphan.txt")
    _check(kept.size_bytes == 1 and kept.metadata.find("\"sha256\":\"" + kept.digest + "\"") >= 0 and kept.metadata.find("\"size_bytes\":1") >= 0 and kept.metadata.find("\"content_addressed\":true") >= 0, "persisted CAS metadata and byte accounting")
    var merged = store.put_bytes_with_metadata("meta", "meta.txt", "{\"z\":1,\"a\":{\"nested\":true}}")
    _check(merged.metadata.find("\"a\":{\"nested\":true}") >= 0 and merged.metadata.find("\"z\":1") >= 0 and merged.metadata.find("\"sha256\":\"") >= 0, "caller metadata canonicalized with reserved CAS fields")
    print(kept.digest)
    print(resolve_uri(root, kept.uri))
    _check(is_fala_reaction_uri(kept.uri), "strict URI accepted")
    _check(not is_fala_reaction_uri("fala-reaction://sha256/not-a-digest"), "malformed URI rejected")
    _check(not is_fala_reaction_uri("fala-reaction://sha256/" + kept.digest + "?extra=1"), "URI query rejected")
    _check(digest_from_fala_reaction_uri(kept.uri) == kept.digest, "digest extraction")
    var invalid_digest_rejected = False
    try:
        _ = digest_from_fala_reaction_uri("fala-reaction://sha256/abc")
    except:
        invalid_digest_rejected = True
    _check(invalid_digest_rejected, "invalid digest raises")
    var listed = store.list_blob_digests()
    var kept_seen = False
    var removed_seen = False
    var orphan_seen = False
    for digest in listed:
        if digest == kept.digest: kept_seen = True
        if digest == removed.digest: removed_seen = True
        if digest == orphan.digest: orphan_seen = True
    _check(kept_seen and removed_seen and orphan_seen, "stored digests listed")
    for index in range(1, len(listed)):
        _check(listed[index - 1] <= listed[index], "blob listing is deterministic")
    var duplicate_delete = List[String]()
    duplicate_delete.append(removed.digest)
    duplicate_delete.append(removed.digest)
    var deleted = store.delete_blobs(duplicate_delete^)
    _check(len(deleted) == 1 and deleted[0] == removed.digest, "duplicate delete is idempotent")
    var references = List[String](); references.append(kept.digest); references.append(merged.digest)
    var candidates = store.collect_garbage(references^, dry_run=True)
    _check(len(candidates) == 1 and candidates[0] == orphan.digest, "GC identifies orphan deterministically")
    var collected = store.collect_garbage(references^, dry_run=False)
    _check(len(collected) == 1 and collected[0] == orphan.digest, "GC deletion preserves reference")
    _check(store.resolve(kept.uri) != "", "referenced blob remains resolvable")
    # Fixed SHA-256 values generated by Python's
    # json.dumps(sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    # for the shared scalar/string subset.  The API accepts JSON text rather
    # than a structured payload; EmberJson's native Float64 spelling is not
    # promised to match Python for every exponent or negative-zero input.
    _check(content_address_json("{\"b\":1,\"a\":[\"ż\",2]}") == "64518e6e774d821af6e21ae142daaa74e778d90bfe92965c286534aeb7603882", "nested key order and unicode")
    _check(content_address_json("{\"z\":{\"b\":[true,null,3.5],\"a\":\"ż\"},\"a\":1}") == "cd94373f7ed0b4c0df95969e585cb727fb41c6d4e9379e23941a7292c6beaf3d", "nested arrays and null")
    _check(content_address_json("{\"text\":\"héllo 世界 🌍\",\"empty\":\"\"}") == "a0fd782b00c62dcbe6d7cdfd4b34350da3a8f564553bec1a64964329f0e8b02d", "unicode strings")
    _check(content_address_json("{\"bool\":true,\"null\":null,\"integer\":42,\"negative\":-7,\"float\":3.5}") == "0eecc792bea223c87f706c0e1f92e9a2ed7bd7a72cb818b1949e4c640a483a50", "scalar types")
    _check(content_address_json("[null,false,0,1.0,\"x\",{\"b\":2,\"a\":1}]") == "00a16bc8b7a1fbadedf4b380908fd690be6aa5c08aa02392c7058a8d6b1a49c0", "array and float")
    _check(content_address_json("{\"controls\":\"line\\nnext\",\"escaped\":\"quote \\\" and \\\\ slash\"}") == "355a3a7eba556ca6da5247fa3101b9eb7d7d1fe31bd845a5e81cfa274eb45c58", "JSON escaping")
    print("reaction CAS/GC parity smoke ok")

